## Correlation between news and stock movement

In [1]:
import os

os.chdir("..")  # set the working directory one level up
from scripts.financial_analyzer import FinancialAnalyzer
from scripts.stock_analyzer import StockAnalyzer

f_analyzer = FinancialAnalyzer()

### load all stock data ,and add `ticker` column

In [2]:
tickers = ["AAPL", "AMZN", "GOOG", "META", "MSFT", "NVDA", "TSLA"]
stock_data = f_analyzer.load_datas(tickers)
stock_data

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Stock
Date,,,,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0,AAPL
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0,AAPL
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0,AAPL
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0,AAPL
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0,AAPL
...,...,...,...,...,...,...,...,...,...
2024-07-24,225.419998,225.990005,214.710007,215.990005,215.990005,167942900,0.0,0.0,TSLA
2024-07-25,216.800003,226.000000,216.229996,220.250000,220.250000,100636500,0.0,0.0,TSLA
2024-07-26,221.190002,222.279999,215.330002,219.800003,219.800003,94604100,0.0,0.0,TSLA
2024-07-29,224.899994,234.270004,224.699997,232.100006,232.100006,129201800,0.0,0.0,TSLA
2024-07-30,232.250000,232.410004,220.000000,222.619995,222.619995,100560300,0.0,0.0,TSLA

### Load normalized `news data`

In [3]:
new_data = f_analyzer.load_data("datasets/raw_analyst_ratings.csv", isPath=True)
new_data.head()